shell:
  program: /usr/bin/fish
items:
  - colors:
      name: 3024 (dark)
      author: Chris Kempson
      primary:
        background: "#090300"
        foreground: "#a5a2a2"
      cursor:
        text: "#090300"
        cursor: "#a5a2a2"
      normal:
        black: "#090300"
        red: "#db2d20"
        green: "#01a252"
        yellow: "#fded02"
        blue: "#01a0e4"
        magenta: "#a16a94"
        cyan: "#b5e4f4"
        white: "#a5a2a2"
      bright:
        black: "#5c5855"
        red: "#db2d20"
        green: "#01a252"
        yellow: "#fded02"
        blue: "#01a0e4"
        magenta: "#a16a94"
        cyan: "#b5e4f4"
        white: "#f7f7f7"
  - theme: 3024.dark
colors:
  name: Ashes (dark)
  author: Chris Kempson
  primary:
    background: "#1c2023"
    foreground: "#c7ccd1"
  cursor:
    text: "#1c2023"
    cursor: "#c7ccd1"
  normal:
    black: "#1c2023"
    red: "#c7ae95"
    green: "#95c7ae"
    yellow: "#aec795"
    blue: "#ae95c7"
    magenta: "#c795ae"
    cyan: "#95aec7"
    white: "#c7ccd1"
  bright:
    black: "#747c84"
    red: "#c7ae95"
    green: "#95c7ae"
    yellow: "#aec795"
    blue: "#ae95c7"
    magenta: "#c795ae"
    cyan: "#95aec7"
    white: "#f3f4f5"
theme: Ashes.dark

font:
  normal:
    family: JetBrainsMono Nerd Font Mono
    style: Regular
  bold:
    family: JetBrainsMono Nerd Font Mono
    style: Bold
  italic:
    family: JetBrainsMono Nerd Font Mono
    style: Italic
